"""add phone column 

Revision ID: bd3158eb76c4
Revises: 3f0f8e31e8e8
Create Date: 2026-01-22 23:11:18.821597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3158eb76c4'
down_revision: Union[str, Sequence[str], None] = '3f0f8e31e8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=False))
        batch_op.create_unique_constraint(
            'uq_users_phone',  # ✅ explicit name
            ['phone']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint(
            'uq_users_phone',  # ✅ same name
            type_='unique'
        )
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
