"""upadate stock quntity field renam

Revision ID: 9c5a63e1476b
Revises: 33f8169b37cf
Create Date: 2026-08-29 21:46:24.899413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5a63e1476b'
down_revision: Union[str, Sequence[str], None] = '33f8169b37cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=False))
    op.drop_column('products', 'stock_quantiy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_quantiy', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'stock_quantity')
    # ### end Alembic commands ###
